<?php
declare(strict_types=1);
require_once __DIR__.'/store.php';
function ensure(bool $ok): void { if (!$ok) { throw new RuntimeException('Test assertion failed.'); } }
function denied(callable $fn): void { try { $fn(); } catch (Throwable $e) { return; } throw new RuntimeException('Expected denial.'); }
function b64(string $v): string { return rtrim(strtr(base64_encode($v),'+/','-_'),'='); }
function config(): array { return ['profile'=>FNCP_Production_Contract::PROFILE,'deploymentId'=>'test_deployment','conversationId'=>'test_round','wordpressOrigin'=>'https://wordpress.test',
    'eventEndpoint'=>'https://participant.test/internal/wordpress/events','consentVersion'=>'reviewed-v1','noticeSha256'=>str_repeat('a',64),
    'serviceRequestKey'=>b64(str_repeat("\x01",32)),'serviceResponseKey'=>b64(str_repeat("\x02",32)),'eventKey'=>b64(str_repeat("\x03",32)),'caFile'=>'/private-test/ca.pem']; }
final class Fixture {
    public ?string $raw=null; public $now=1789390000000; public $onSwap=null; public array $c; public FNCP_Production_Store $store;
    function __construct() { $this->c=config(); $this->restart(); }
    function restart(): void { $this->store=new FNCP_Production_Store($this->c,fn()=>$this->raw,function($old,$next) { if ($this->onSwap) { $hook=$this->onSwap; $this->onSwap=null; $hook(); return false; } if ($this->raw!==$old) { return false; } $this->raw=$next; return true; },function($new) { if ($this->raw!==null) { return false; } $this->raw=$new; return true; },function() { if ($this->now instanceof Throwable) { throw $this->now; } return $this->now; }); }
    function receipt(string $account='A',?string $id=null): array { return ['schemaVersion'=>1,'deploymentId'=>'test_deployment','conversationId'=>'test_round','receiptId'=>$id??FNCP_Production_Contract::uuid4(),'accountId'=>'acct_'.str_repeat($account,43),
        'consentVersion'=>'reviewed-v1','noticeSha256'=>str_repeat('a',64),'adultSelfAttested'=>true,'eligibilitySelfAttested'=>true,'registrationConsent'=>true,'issuedAt'=>intdiv($this->now,1000),'expiresAt'=>intdiv($this->now,1000)+60]; }
    function wire(string $action,array $body,?string $raw=null): array { $raw??=FNCP_Production_Contract::canonical($body); $stamp=(string)intdiv(is_int($this->now)?$this->now:1789390000000,1000); return [$action,$raw,$stamp,'sha256='.FNCP_Production_Contract::mac(FNCP_Production_Contract::REQUEST_DOMAIN.$action."\n".$stamp.'.'.$raw,$this->c['serviceRequestKey'])]; }
    function call(string $action,array $body): array { return $this->decode($action,$this->store->rpc(...$this->wire($action,$body))); }
    function decode(string $action,array $e): array { FNCP_Production_Contract::exact($e,['payload','signature']); ensure(hash_equals(FNCP_Production_Contract::mac(FNCP_Production_Contract::RESPONSE_DOMAIN.$action."\n".$e['payload'],$this->c['serviceResponseKey']),$e['signature'])); return json_decode(base64_decode(strtr($e['payload'],'-_','+/')),true,8,JSON_THROW_ON_ERROR); }
    function status(string $account='A'): array { return $this->call('status',['schemaVersion'=>1,'deploymentId'=>'test_deployment','conversationId'=>'test_round','accountId'=>'acct_'.str_repeat($account,43),'nonce'=>str_repeat('N',43)]); }
}
$tests=[];function test(string $name,callable $fn):void {global $tests;$fn();$tests[]=$name;}
test('configuration is exact, HTTPS-only, independent decoded32 keys and no synthetic switch',function(){ $c=config();ensure(FNCP_Production_Contract::configuration($c)===$c);foreach(['wordpressOrigin'=>'http://wordpress.test','eventEndpoint'=>'https://participant.test/wrong','serviceResponseKey'=>$c['serviceRequestKey'],'serviceRequestKey'=>str_repeat('X',43),'profile'=>'SYNTHETIC_ONLY','noticeSha256'=>'bad'] as $k=>$v){$b=$c;$b[$k]=$v;denied(fn()=>FNCP_Production_Contract::configuration($b));}$c['extra']=true;denied(fn()=>FNCP_Production_Contract::configuration($c)); });
test('unsigned altered expired timestamp and duplicate-key requests do not register',function(){ $f=new Fixture;$b=$f->receipt();$w=$f->wire('register',$b);$w[3]='sha256='.str_repeat('0',64);denied(fn()=>$f->store->rpc(...$w));$raw=FNCP_Production_Contract::canonical($b);$raw=substr($raw,0,-1).',"schemaVersion":1}';denied(fn()=>$f->store->rpc(...$f->wire('register',$b,$raw)));$w=$f->wire('register',$b);$f->now+=31000;denied(fn()=>$f->store->rpc(...$w));ensure(count(json_decode($f->raw,true)['registrations'])===0); });
test('registration returns only signed immutable reference and remains pending',function(){ $f=new Fixture;$r=$f->call('register',$f->receipt());FNCP_Production_Contract::exact($r,['schemaVersion','deploymentId','conversationId','receiptId','registrationId','status']);ensure($r['status']==='SUBMITTED_NOT_APPROVED');$s=$f->status();ensure($s['state']==='pending'&&$s['version']===0&&!$s['deliveryPending']&&$s['registrationId']===$r['registrationId']); });
test('same committed receipt retries after expiry and process restart without another identity',function(){ $f=new Fixture;$b=$f->receipt();$a=$f->call('register',$b);$f->now+=120000;$f->restart();ensure($f->call('register',$b)===$a);ensure(count(json_decode($f->raw,true)['registrations'])===1);denied(fn()=>$f->call('register',$f->receipt())); });
test('new expired receipt and changed committed receipt or account are rejected',function(){ $f=new Fixture;$b=$f->receipt();$f->call('register',$b);$bad=$b;$bad['expiresAt']--;denied(fn()=>$f->call('register',$bad));$bad=$b;$bad['accountId']='acct_'.str_repeat('B',43);denied(fn()=>$f->call('register',$bad));$expired=$f->receipt('C');$f->now+=61000;denied(fn()=>$f->call('register',$expired));ensure(count(json_decode($f->raw,true)['registrations'])===1); });
test('wrong deployment round notice declarations and browser-selected fields fail',function(){ $f=new Fixture;foreach(['deploymentId'=>'other','conversationId'=>'other','consentVersion'=>'old','noticeSha256'=>str_repeat('b',64),'adultSelfAttested'=>false,'eligibilitySelfAttested'=>'true','registrationConsent'=>false,'accountId'=>'email@example.test']as$k=>$v){$b=$f->receipt();$b[$k]=$v;denied(fn()=>$f->call('register',$b));}$b=$f->receipt();$b['email']='private-sentinel@example.test';denied(fn()=>$f->call('register',$b)); });
test('last lifetime slot race admits exactly one and no slot is freed by revocation',function(){ $f=new Fixture;foreach(range('A','S')as$a){$f->call('register',$f->receipt($a));}$loser=$f->receipt('T');$winner=$f->receipt('U');$f->onSwap=function()use($f,$winner){$f->call('register',$winner);};denied(fn()=>$f->call('register',$loser));ensure(count(json_decode($f->raw,true)['registrations'])===20);$id=$f->status('A')['registrationId'];$f->store->decide($id,'revoked');denied(fn()=>$f->call('register',$f->receipt('V'))); });
test('duplicate account race resolves exact retry once and conflicts never relink',function(){ $f=new Fixture;$b=$f->receipt();$f->status();$f->onSwap=function()use($f,$b){$f->call('register',$b);};$r=$f->call('register',$b);ensure(count(json_decode($f->raw,true)['registrations'])===1);ensure($r['registrationId']===$f->status()['registrationId']); });
test('approval and immutable event commit together, repeated decision idempotent',function(){ $f=new Fixture;$id=$f->call('register',$f->receipt())['registrationId'];$e=$f->store->decide($id,'approved');ensure($e==$f->store->decide($id,'approved'));$s=$f->status();ensure($s['state']==='approved'&&$s['version']===1&&$s['deliveryPending']&&$s['decisionEventId']===$e['event']['eventId']);ensure(count(json_decode($f->raw,true)['events'])===1); });
test('revocation from pending is version2 and terminal through restart',function(){ $f=new Fixture;$id=$f->call('register',$f->receipt())['registrationId'];$e=$f->store->decide($id,'revoked');ensure($e['event']['version']===2);$f->restart();denied(fn()=>$f->store->decide($id,'approved'));ensure($f->store->decide($id,'revoked')==$e);ensure($f->status()['state']==='revoked'); });
test('concurrent approve versus revoke cannot overwrite terminal authority',function(){ $f=new Fixture;$id=$f->call('register',$f->receipt())['registrationId'];$f->onSwap=function()use($f,$id){$f->store->decide($id,'revoked');};denied(fn()=>$f->store->decide($id,'approved'));ensure($f->status()['version']===2); });
test('all20 approved accounts retain terminal removal capacity and never exceed40 events',function(){ $f=new Fixture;$ids=[];foreach(array_merge(range('A','T'))as$a){$id=$f->call('register',$f->receipt($a))['registrationId'];$ids[]=$id;$f->store->decide($id,'approved');}foreach($ids as$id){$f->store->decide($id,'revoked');}$s=json_decode($f->raw,true);ensure(count($s['events'])===40&&count($s['registrations'])===20);foreach($f->store->pending()as$i=>$r){ensure($r['event']['version']===($i<20?2:1));} });
test('lost acknowledgement retries exact body with fresh timestamp and new signature',function(){ $f=new Fixture;$id=$f->call('register',$f->receipt())['registrationId'];$e=$f->store->decide($id,'approved');$one=$f->store->delivery($e['event']['eventId']);$f->store->deliveryResult($e['event']['eventId'],false,'TRANSPORT_UNAVAILABLE');$f->now+=1000;$f->restart();$two=$f->store->delivery($e['event']['eventId']);ensure($one['body']===$two['body']&&$one['event']===$two['event']&&$one['timestamp']!==$two['timestamp']&&$one['signature']!==$two['signature']); });
test('acknowledgement matches exact200 ID and integer version, late failure cannot undo ACK',function(){ $f=new Fixture;$id=$f->call('register',$f->receipt())['registrationId'];$e=$f->store->decide($id,'approved')['event'];$ack=['ok'=>true,'eventId'=>$e['eventId'],'version'=>1];ensure(FNCP_Production_Contract::acknowledged(200,json_encode($ack),$e));ensure(!FNCP_Production_Contract::acknowledged(202,json_encode($ack),$e));$ack['version']='1';ensure(!FNCP_Production_Contract::acknowledged(200,json_encode($ack),$e));$f->store->deliveryResult($e['eventId'],true,'ACKNOWLEDGED');$f->store->deliveryResult($e['eventId'],false,'ACK_REJECTED');ensure(!$f->status()['deliveryPending']&&$f->store->delivery($e['eventId'])===null); });
test('failed revocation delivery is immediately visible and precedes stale approval',function(){ $f=new Fixture;$id=$f->call('register',$f->receipt())['registrationId'];$a=$f->store->decide($id,'approved');$r=$f->store->decide($id,'revoked');$f->store->deliveryResult($r['event']['eventId'],false,'TRANSPORT_UNAVAILABLE');$f->store->deliveryResult($a['event']['eventId'],true,'ACKNOWLEDGED');$s=$f->status();ensure($s['state']==='revoked'&&$s['version']===2&&$s['deliveryPending']); });
test('status binds account nonce and current observation with no secret or raw identity claim',function(){ $f=new Fixture;$s=$f->status();FNCP_Production_Contract::exact($s,['schemaVersion','deploymentId','conversationId','accountId','nonce','registrationId','state','version','decisionEventId','deliveryPending','observedAt']);ensure($s['state']==='unregistered'&&$s['registrationId']===null&&$s['nonce']===str_repeat('N',43)); });
test('millisecond backward clock permanently closes across workers and correction',function(){ $f=new Fixture;$f->call('register',$f->receipt());$f->now--;denied(fn()=>$f->status());ensure(json_decode($f->raw,true)['clockClosed']);$f->now+=10000;$f->restart();denied(fn()=>$f->status()); });
test('clock fault survives losingCAS to healthyworker and corrected time',function(){ $f=new Fixture;$f->status();$f->now--;$f->onSwap=function()use($f){$f->now+=2;$f->restart();$f->status();};denied(fn()=>$f->status());ensure(json_decode($f->raw,true)['clockClosed']);$f->now+=1000;denied(fn()=>$f->status()); });
test('invalid and throwing clocks persist terminal closure',function(){foreach([null,-1,NAN,'1789390000000',new RuntimeException('secret-sentinel')]as$clock){$f=new Fixture;$f->status();$f->now=$clock;denied(fn()=>$f->store->adminRows());ensure(json_decode($f->raw,true)['clockClosed']);} });
test('configuration replacement and corrupt event linkage deny instead of adoption',function(){ $f=new Fixture;$id=$f->call('register',$f->receipt())['registrationId'];$f->store->decide($id,'approved');$original=$f->raw;$s=json_decode($f->raw,true);$eid=$s['registrations'][$id]['decisionEventId'];$s['events'][$eid]['event']['accountId']='acct_'.str_repeat('B',43);$f->raw=FNCP_Production_Contract::canonical($s);denied(fn()=>$f->status());$f->raw=$original;$f->c['conversationId']='new_round';$f->restart();denied(fn()=>$f->store->adminRows()); });
test('admin projection excludes accounts receipt bodies and credentials',function(){ $f=new Fixture;$f->call('register',$f->receipt());$rows=$f->store->adminRows();FNCP_Production_Contract::exact($rows[0],['registrationId','consentVersion','noticeSha256','createdAt','state','version','delivery']);ensure(!str_contains(json_encode($rows),'acct_')); });
echo json_encode(['result'=>'PASS','tests'=>count($tests),'classification'=>'PURE_PHP_PRODUCTION_CONTRACT_MODEL','checks'=>$tests],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)."\n";
