ServerName wordpress:8443
ServerTokens Prod
ServerSignature Off
SSLSessionCache none
<VirtualHost *:8443>
    ServerName wordpress:8443
    DocumentRoot /usr/src/wordpress
    SSLEngine on
    SSLCertificateFile /run/fncp/wordpress/server.pem
    SSLCertificateKeyFile /run/fncp/wordpress/server-key.pem
    SSLProtocol -all +TLSv1.2 +TLSv1.3
    ErrorLog /proc/self/fd/2
    CustomLog /dev/null combined
    LimitRequestBody 32768
    RequestReadTimeout header=5-10,MinRate=500 body=5,MinRate=500
    <LocationMatch "^/(wp-admin/(install|setup-config|upgrade)\.php|xmlrpc\.php|wp-cron\.php)$">
        Require all denied
    </LocationMatch>
    <Directory /usr/src/wordpress>
        Options -Indexes +FollowSymLinks
        AllowOverride None
        Require all granted
        DirectoryIndex index.php
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule . /index.php [L]
    </Directory>
</VirtualHost>
