import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,writeFileSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawnSync} from 'node:child_process';
const modulePath=new URL('./material.php',import.meta.url).pathname;
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'fncp-wp-tls-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const run=args=>{const r=spawnSync('openssl',args,{stdio:['ignore','pipe','pipe'],timeout:10000});assert.equal(r.status,0);};run(['req','-x509','-newkey','ec','-pkeyopt','ec_paramgen_curve:prime256v1','-nodes','-days','1','-subj','/CN=QA CA','-addext','basicConstraints=critical,CA:TRUE','-keyout',join(dir,'ca.key'),'-out',join(dir,'ca.pem')]);run(['req','-new','-newkey','ec','-pkeyopt','ec_paramgen_curve:prime256v1','-nodes','-subj','/CN=QA leaf','-keyout',join(dir,'leaf.key'),'-out',join(dir,'leaf.csr')]);writeFileSync(join(dir,'leaf.ext'),'subjectAltName=DNS:wordpress,IP:127.0.0.1\nbasicConstraints=critical,CA:FALSE\nextendedKeyUsage=serverAuth\n');run(['x509','-req','-in',join(dir,'leaf.csr'),'-CA',join(dir,'ca.pem'),'-CAkey',join(dir,'ca.key'),'-CAcreateserial','-days','1','-extfile',join(dir,'leaf.ext'),'-out',join(dir,'leaf.pem')]);return Object.fromEntries(['ca.pem','ca.key','leaf.pem','leaf.key'].map(n=>[n,readFileSync(join(dir,n),'utf8')]));}
function verify(x){const code=`require $argv[1]; $x=json_decode(stream_get_contents(STDIN),true,8,JSON_THROW_ON_ERROR); try { if($x['kind']==='ca') fncp_runtime_validate_ca($x['pem'],$x['now']); else fncp_runtime_validate_leaf($x['pem'],$x['key'],$x['origin'],$x['now']); echo 'PASS'; } catch(Throwable $e) { exit(1); }`;return spawnSync('php',['-r',code,modulePath],{input:JSON.stringify({now:Math.floor(Date.now()/1000),...x}),encoding:'utf8',timeout:5000}).status;}
test('normal WordPress TLS accepts exact DNS and IPv4 SANs and private CA',t=>{const h=fixture(t);assert.equal(verify({kind:'ca',pem:h['ca.pem']}),0);for(const origin of ['https://wordpress:8443','https://127.0.0.1:8443'])assert.equal(verify({kind:'leaf',pem:h['leaf.pem'],key:h['leaf.key'],origin}),0);});
test('wrong host, mismatched key, CA-as-leaf and expired leaf reject',t=>{const h=fixture(t),x={kind:'leaf',pem:h['leaf.pem'],key:h['leaf.key'],origin:'https://wordpress:8443'};for(const patch of [{origin:'https://other.invalid'},{key:h['ca.key']},{pem:h['ca.pem'],key:h['ca.key']},{now:Math.floor(Date.now()/1000)+172800}])assert.equal(verify({...x,...patch}),1);});
test('CA bundle rejects malformed content, appended private key, non-CA leaf and expiry',t=>{const h=fixture(t);for(const pem of ['not a certificate',h['ca.pem']+h['ca.key'],h['leaf.pem'],h['ca.pem']+'unexpected'])assert.equal(verify({kind:'ca',pem}),1);assert.equal(verify({kind:'ca',pem:h['ca.pem'],now:Math.floor(Date.now()/1000)+172800}),1);});
