import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, realpathSync, chmodSync, mkdirSync, writeFileSync, readFileSync, rmSync, symlinkSync, linkSync, renameSync, existsSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { createMaterialCustody, acquireServiceLock, privateDirectory } from './custody.mjs';
const denied={message:'Private service material rejected.'};
function fixture(t){const directory=realpathSync(mkdtempSync(join(tmpdir(),'fncp-custody-test-')));chmodSync(directory,0o700);t.after(()=>rmSync(directory,{recursive:true,force:true}));const file=(name,body='synthetic-private-value',mode=0o600)=>{const path=join(directory,name);writeFileSync(path,body,{mode});return path;};return{directory,file};}
function childLock(directory){const script=`import {readFileSync} from 'node:fs';import {acquireServiceLock} from ${JSON.stringify(new URL('./custody.mjs',import.meta.url).href)};try{const lock=acquireServiceLock(JSON.parse(readFileSync(0,'utf8')));lock.release();process.stdout.write('ACQUIRED');}catch(e){if(e.message!=='Private service material rejected.')process.exit(2);process.stdout.write('DENIED');}`;const r=spawnSync(process.execPath,['--input-type=module','-e',script],{input:JSON.stringify(directory),encoding:'utf8',timeout:5000,maxBuffer:8192});assert.equal(r.error,undefined);assert.equal(r.status,0);assert.equal(r.stderr,'');return r.stdout;}

test('directory contract rejects aliases, symlinks and every nonprivate permission bit',t=>{const h=fixture(t);assert.ok(privateDirectory(h.directory).isDirectory());assert.throws(()=>privateDirectory(h.directory+'/.'),denied);const link=join(h.directory,'alias');symlinkSync(h.directory,link);assert.throws(()=>privateDirectory(link),denied);for(const mode of [0o750,0o701,0o1700]){chmodSync(h.directory,mode);assert.throws(()=>privateDirectory(h.directory),denied);}chmodSync(h.directory,0o700);});
test('captured owned 0400 and 0600 files verify by identity and bytes independently of caller buffer',t=>{const h=fixture(t),c=createMaterialCustody();const one=h.file('one'),two=h.file('two','second',0o400);const bytes=c.read(one);c.read(two);bytes.fill(0);assert.equal(c.verify(),true);assert.equal(Object.keys(c.fingerprints()).length,2);assert.ok(Object.isFrozen(c.fingerprints()));c.close();assert.throws(()=>c.read(one),denied);assert.throws(()=>c.verify(),denied);});
test('empty oversized permissive special-mode symlink and hardlinked files are rejected',t=>{const h=fixture(t),c=createMaterialCustody();assert.throws(()=>c.read(h.file('empty','')),denied);assert.throws(()=>c.read(h.file('large','12345'),4),denied);for(const mode of [0o644,0o660,0o1600]){const p=h.file('mode-'+mode);chmodSync(p,mode);assert.throws(()=>c.read(p),denied);}const p=h.file('regular'),link=join(h.directory,'link');symlinkSync(p,link);assert.throws(()=>c.read(link),denied);rmSync(link);linkSync(p,link);assert.throws(()=>c.read(p),denied);c.close();});
test('same-size material edits and same-byte inode replacements cannot be adopted',t=>{const h=fixture(t),c=createMaterialCustody(),p=h.file('secret','AAAA');c.read(p);writeFileSync(p,'BBBB');assert.throws(()=>c.verify(),denied);writeFileSync(p,'AAAA');assert.equal(c.verify(),true);renameSync(p,p+'.old');writeFileSync(p,'AAAA',{mode:0o600});assert.throws(()=>c.verify(),denied);c.close();});
test('parent-directory replacement is rejected even with unchanged captured file bytes',t=>{const h=fixture(t),directory=join(h.directory,'material');mkdirSync(directory,{mode:0o700});const p=join(directory,'secret');writeFileSync(p,'value',{mode:0o600});const c=createMaterialCustody();c.read(p);renameSync(directory,directory+'.old');mkdirSync(directory,{mode:0o700});writeFileSync(p,'value',{mode:0o600});assert.throws(()=>c.verify(),denied);c.close();});
test('second read cannot adopt a replacement parent while the exact original file inode is moved into it',t=>{const h=fixture(t),directory=join(h.directory,'material');mkdirSync(directory,{mode:0o700});const p=join(directory,'secret');writeFileSync(p,'value',{mode:0o600});const c=createMaterialCustody();c.read(p);const before=statSync(p);renameSync(directory,directory+'.old');mkdirSync(directory,{mode:0o700});renameSync(join(directory+'.old','secret'),p);assert.equal(statSync(p).ino,before.ino);assert.throws(()=>c.read(p),denied);assert.throws(()=>c.verify(),denied);c.close();});
test('exclusive service lock refuses a second process without changing its owner and clean release permits acquisition',t=>{const h=fixture(t),lock=acquireServiceLock(h.directory),path=join(h.directory,'service.lock'),before=readFileSync(path);t.after(()=>{try{lock.release();}catch{}});assert.equal(statSync(path).mode&0o7777,0o600);assert.equal(childLock(h.directory),'DENIED');assert.deepEqual(readFileSync(path),before);assert.equal(lock.verify(),true);lock.release();assert.equal(existsSync(path),false);assert.equal(childLock(h.directory),'ACQUIRED');assert.equal(existsSync(path),false);assert.throws(()=>lock.verify(),denied);});
test('pre-existing service lock is never adopted or removed',t=>{const h=fixture(t),p=h.file('service.lock','abandoned-owner');assert.equal(childLock(h.directory),'DENIED');assert.equal(readFileSync(p,'utf8'),'abandoned-owner');});
test('lock release preserves a substituted owner path and rejects permission drift',t=>{const h=fixture(t),lock=acquireServiceLock(h.directory),p=join(h.directory,'service.lock');chmodSync(p,0o640);assert.throws(()=>lock.verify(),denied);chmodSync(p,0o600);renameSync(p,p+'.old');writeFileSync(p,'replacement',{mode:0o600});assert.throws(()=>lock.release(),denied);assert.equal(readFileSync(p,'utf8'),'replacement');});
