/** Fixed review scope, not a deployment specification. No runtime configuration. */
const component = (id, kind, sources, gap) => ({ id, kind, sources, gap });
const components = [
  component('polis-server', 'POLIS_IMAGE', ['server/Dockerfile', 'server/package.json', 'server/package-lock.json', 'server/src/auth/fncp-production-admission.ts', 'server/src/auth/fncp-participant-policy.ts', 'server/src/auth/fncp-gateway.ts', 'server/src/fncp-provider-policy.ts', 'server/src/routes/fncp-provider-allowlist.ts'], 'Dedicated fncp-production target must be built from the reviewed release; source hashes do not establish its image digest, provenance or current security status.'),
  component('polis-math', 'POLIS_IMAGE', ['math/Dockerfile', 'math/deps.edn'], 'deps.edn is a dependency declaration, not a complete transitive lock or measured runtime JAR inventory; the exact built worker needs fresh assurance.'),
  component('polis-alpha', 'POLIS_IMAGE', ['client-participation-alpha/Dockerfile', 'client-participation-alpha/package.json', 'client-participation-alpha/package-lock.json', 'client-participation-alpha/src/lib/fncp-gateway-context.server.ts'], 'The alpha artifact requires exact release packaging, server-side gateway binding and current image assurance; UI tests do not establish deployment identity.'),
  component('polis-proxy', 'POLIS_IMAGE', ['deploy/fncp/nginx/Dockerfile', 'deploy/fncp/nginx/fncp-staging.conf'], 'The current proxy configuration is synthetic loopback QA, not reviewed production HTTPS, private upstream topology or public closure assurance.'),
  component('polis-migration', 'POLIS_IMAGE', ['server/Dockerfile-migrate', 'server/bin/fncp-run-migrations.sh'], 'The short-lived migration artifact is a separate fifth application image; migration SQL closure and a target-specific pre-migration recovery checkpoint require separate review.'),
  component('polis-postgresql', 'INFRASTRUCTURE', ['server/Dockerfile-db', 'deploy/fncp/docker-compose.staging.yml'], 'The disposable QA PostgreSQL server is outside the five application images. Production provider, supported version, TLS, access isolation, maintenance and restore ownership are unselected.'),
  component('wordpress-core-php', 'HOST_SOURCE', ['deploy/fncp/wordpress-identity/runtime.mjs', 'deploy/fncp/local-wordpress-runtime/router.php', 'deploy/fncp/local-wordpress-runtime/prepare.mjs'], 'WordPress core is a separately verified archive in private local runtime, which this command does not read. Host PHP and production WordPress packaging, extensions, patching and server configuration are not covered by the five images.'),
  component('wordpress-plugins', 'HOST_SOURCE', ['deploy/fncp/wordpress-identity/fncp-wordpress-identity.php', 'deploy/fncp/wordpress-identity/registry.php', 'deploy/fncp/wordpress-identity/contract.php', 'deploy/fncp/wordpress-local/fncp-wordpress-local.php', 'deploy/fncp/wordpress-local/journal.php', 'deploy/fncp/wordpress-local/contract.php'], 'These are synthetic-only registration and approval/outbox plugins, not an approved live WordPress deployment. Self-attestation and round approval do not verify Indigenous heritage.'),
  component('wordpress-mysql', 'INFRASTRUCTURE', ['deploy/fncp/local-wordpress-runtime/compose.yml'], 'The digest-pinned MySQL declaration belongs to isolated local QA, not a chosen production database, current scan, authenticated live instance or recovery service.'),
  component('browser-bff-registration', 'HOST_SOURCE', ['deploy/fncp/local-browser/browser-server.mjs', 'deploy/fncp/local-browser/start.mjs', 'deploy/fncp/local-browser/public/app.js', 'deploy/fncp/local-browser/public/index.html', 'deploy/fncp/local-browser/public/style.css', 'deploy/fncp/wordpress-identity/server-registration.mjs', 'deploy/fncp/wordpress-identity/registration-issuer.mjs', 'deploy/fncp/wordpress-identity/wordpress-client.mjs'], 'The loopback BFF and private registration bridge are host-side Node code, absent from the five images. Production HTTPS callbacks, Secure cookies, packaging, session topology and issuer integration remain unimplemented.'),
  component('access-ledger', 'HOST_SOURCE', ['deploy/fncp/local-access/access-server.mjs', 'deploy/fncp/local-access/round-control.mjs', 'deploy/fncp/local-access/start.mjs', 'deploy/fncp/local-access/staging-config.mjs'], 'Strict access and invitation state use the local Node SQLite proof. Production packaging, process supervision, multi-instance consistency and target-specific durable storage are not established.'),
component('identity-adapter', 'HOST_SOURCE', ['deploy/fncp/identity-foundation/identity.mjs', 'deploy/fncp/identity-foundation/bounded-response.mjs', 'deploy/fncp/identity-foundation/package.json', 'deploy/fncp/identity-foundation/package-lock.json', 'deploy/fncp/identity-foundation/synthetic-browser-driver.mjs'], 'The OIDC library is locked separately from Pol.is server and alpha. Its driver injects invented signed responses; no real issuer callback, verified mailbox or production identity service is established.'),
  component('activation-ledger', 'HOST_SOURCE', ['deploy/fncp/activation-foundation/authority.mjs', 'deploy/fncp/activation-foundation/controlled-access.mjs'], 'The local signed-lease verifier and SQLite authority are not a production approval service. Independent operator authentication, signer custody, trusted release measurement and rollback protection remain required.'),
  component('wordpress-event-receiver', 'HOST_SOURCE', ['deploy/fncp/local-access/wordpress-receiver.mjs', 'deploy/fncp/local-access/wordpress-events.mjs'], 'The signed loopback event receiver is separate host-side code. Production transport, secret delivery/rotation, durable retry ownership and authenticated operator workflows remain unintegrated.'),
  component('coordinated-recovery', 'HOST_SOURCE', ['deploy/fncp/expanded-recovery/run.mjs', 'deploy/fncp/expanded-recovery/crypto.mjs', 'deploy/fncp/expanded-recovery/restore-sqlite.mjs', 'deploy/fncp/expanded-recovery/wordpress-contract.mjs'], 'Actual isolated four-store recovery was a bounded local proof. A selected production backup destination, independent key custody, RPO/RTO, complete cold application restart and real-issuer assurance remain outstanding.'),
  component('real-idp', 'EXTERNAL_DEPENDENCY', [], 'No production identity provider, tenant/client configuration, exact HTTPS redirect, email verification policy or operator MFA flow has been selected and proven.'),
  component('mail-delivery', 'EXTERNAL_DEPENDENCY', ['deploy/fncp/local-access/capture-mail.mjs'], 'Mail currently uses private local capture and WordPress delivery suppression. No real delivery service, approved sender, DNS authentication, bounce handling or approved external test is configured.'),
  component('hosting-network-tls', 'EXTERNAL_DEPENDENCY', [], 'C1/C2/C3 hosting choice, region, architecture, DNS/TLS, isolated database networks and approved closed deployment are not selected. No production infrastructure is generated here.'),
  component('operator-signing-secrets', 'EXTERNAL_DEPENDENCY', [], 'A named accountable operator, independent MFA approval path, secret store, signer separation and rotation/recovery procedure require owner decisions; no private key or live configuration is inventoried.'),
  component('operations-assurance', 'EXTERNAL_DEPENDENCY', [], 'Monitoring, alert ownership, patch/incident runbooks, fresh whole-release SBOM/scans, required remote CI, review and separate closed-release approval remain required. Historical five-image evidence cannot cover the whole system.'),
];
const sourcePaths = [...new Set(components.flatMap(entry => entry.sources))];
const dependencyFiles = ['server/package.json', 'server/package-lock.json', 'math/deps.edn', 'client-participation-alpha/package.json', 'client-participation-alpha/package-lock.json', 'deploy/fncp/identity-foundation/package.json', 'deploy/fncp/identity-foundation/package-lock.json'];
function freeze(value) { for (const child of Object.values(value)) if (child && typeof child === 'object') freeze(child); return Object.freeze(value); }
export const FIXED_MANIFEST = freeze({ schemaVersion: 1, components, sourcePaths, dependencyFiles });
