# syntax=docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc
# Normal-start derivative; separately provisioned datadir is required.
FROM docker.io/library/mariadb@sha256:9249261993db977032af3b0ff7369af07ea13216f61d77b30a243ccb2b2ffc04
RUN test -f /usr/local/bin/gosu \
    && rm /usr/local/bin/gosu \
    && test ! -e /usr/local/bin/gosu \
    && test "$(id -u mysql)" = 999 \
    && mariadbd --version
USER 999:999
ENTRYPOINT ["mariadbd"]
CMD []
ARG SOURCE_REVISION
RUN case "$SOURCE_REVISION" in ""|*[!0-9a-f]*) exit 1 ;; esac && test "${#SOURCE_REVISION}" -eq 40
LABEL org.opencontainers.image.revision="$SOURCE_REVISION" org.opencontainers.image.base.digest="sha256:9249261993db977032af3b0ff7369af07ea13216f61d77b30a243ccb2b2ffc04" org.barayamal.fncp.profile="FNCP_MARIADB_NORMAL_V1"
