name: Run Jest Tests - client admin

concurrency:
  group: jest-client-admin-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - 'client-admin/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: client-admin/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: client-admin

      - name: Run Jest tests with coverage
        run: npm run test:coverage
        working-directory: client-admin

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
        with:
          directory: client-admin/coverage
          flags: client-admin
          name: client-admin-coverage
          fail_ci_if_error: false
