name: Generate Sensemaker report

on: workflow_dispatch

jobs:
  generate-summary:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          repository: "tevko/sensemaking-tools"
          ref: 988ad3547a9b5c3fe92fa6cd2bbff9837795fb6b
          path: sensemaking-tools

      - uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Setup Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          cache-dependency-path: sensemaking-tools/package-lock.json
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: sensemaking-tools

      - name: Get CSV
        uses: valitydev/action-download-file@9563a0636fce0f567283bb3167729fccb96a1fae # v1
        with:
          url: https://preprod.pol.is/api/v3/reportExport/r7kfpvrhdpyykbhnirtcd/comment-groups.csv
          target-path: sensemaking-tools/data/

      - name: Modify CSV headers
        run: |
          ls -l data/
          file="data/comment-groups.csv"
          new_header="comment-id,comment_text,total-votes,total-agrees,total-disagrees,total-passes,group-a-votes,group-0-agree-count,group-0-disagree-count,group-0-pass-count,group-b-votes,group-1-agree-count,group-1-disagree-count,group-1-pass-count"
          sed -i "1s/.*/$new_header/" "$file"
        working-directory: sensemaking-tools

      - name: List Files
        run: ls -l sensemaking-tools/
      
      - name: Generate Summary Output
        run: |
          npx ts-node runner-cli/runner.ts --outputFile "summary" \
          --vertexProject "jigsaw-vertex-integration" \
          --inputFile "data/comment-groups.csv"
        # run: |
        #   echo "<html>test</html>" > summary.html
        working-directory: sensemaking-tools

      - name: Upload HTML as Artifact
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3
        with:
          name: sensemaking-summary-html
          path: sensemaking-tools/summary.html

  use_html:
    needs: generate-summary
    runs-on: ubuntu-latest
    steps:
      - name: Download HTML Artifact
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: sensemaking-summary-html
          path: downloaded-html
      # - name: Checkout
      #   uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: debug
        run: |
          ls -al
          ls -al downloaded-html
      - name: Deploy to gist
        uses: exuanbo/actions-deploy-gist@47697fceaeea2006a90594ee24eb9cd0a1121ef8 # v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 2ea3c0f4cadffbde9c414c8d203cd599
          file_path: downloaded-html/summary.html
          file_type: html
